### ISSUE TITLE
"Milking failed" message freezes input on Android

### ISSUE THREAD

**Issue by Namain** [urbanyeti/stardew-better-ranching#9]
I've recently started trying this mod on Android. When I attempt to milk a cow who can't be milked, I get the expected "Milking Failed" message, but after that the game stops paying attention to my inputs. I can press anywhere on the touchscreen and nothing happens until I force close the app and re-open it. 

The clock still continues to count and animals continue to move around, so the game isn't frozen, but I'm not able to do anything.

Android is still stuck on Stardew 1.4.5.148 and SMAPI 3.7.6, so I'm using Better Ranching 1.7.6.

**Comment by teohhanhui** [comment]
It also shows "milking failed" when using [tap-to-move & auto-attack](https://stardewvalleywiki.com/Mobile_Controls#Tap-to-move_.26_Auto-Attack) (the default controls).

### Steps to reproduce
1. Equip the milk pail.
2. Tap on an animal.

### Expected behaviour
1. Player auto moves towards the tapped animal.
2. Player auto turns around in the right direction.
2. Player auto milks the tapped animal.

### Actual behaviour
1. "Milking failed" and nothing happens.

This makes the mod practically unusable on Android.

**Comment by teohhanhui** [comment]
### Workaround
In `config.json`:

* Set `PreventFailedHarvesting` to `false`.
* Set `PreventHarvestRepeating` to `false`.

**Comment by urbanyeti** [comment]
That functionality doesn't really work with tap to move and & auto-attack and I don't have an android device so can't really test any enhancements out myself so teohhanhui's workaround of disabling the feature is the best option for the time being. :/
